update and test Arduin Create using OpenVINO 2018 R4.0
TODO: Car Detection steps 3 and 4 do not compile giving the error during link:
undefined reference to `InferenceEngine::make_shared_blob(std::shared_ptr<InferenceEngine::Blob> const&, InferenceEngine::ROI const&)'
It is suspected that the funtion that is declared at the end of ie_blob.h is missing from the libinference_engine.so or other library used during linking on the Arduino Create server.  The error is being reported so that someone with access to the Arduino Create library source can troubleshoot.

Note: Last working version was R1.2, R2.x and R3.x  were not possible due to state of library used by the web Arduino Create.  R4.0 appears to now be in place, which now makes R1.2 obsolete.